steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/gcp-alloydb/payments/payment-bank-app", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/gcp-alloydb/payments/payment-bank-app"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "payment-bank-app",
        "--image",
        "gcr.io/$gcp-alloydb/payments/payment-bank-app",
        "--region",
        "europe-west2-london",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        
      ]

images:
  - "gcr.io/$gcp-alloydb/payments/payment-bank-app"

options:
  logging: CLOUD_LOGGING_ONLY
